# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven Wrapper"
  homepage: https://maven.apache.org/tools/wrapper
  labels:
    - java
    - build-management
    - apache-maven
    - maven
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  del_branch_on_merge: true
  features:
    issues: true

notifications:
  commits: commits@maven.apache.org
  #issues: issues@maven.apache.org
  #pullrequests: issues@maven.apache.org
